/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;

public class App {

    public static void main(final String[] args) throws IOException {
        try {
            String fileName = args[0];
            Bitmap bitmap = new Bitmap(fileName);
            String requiredColor = args[2];
            switch (requiredColor) {
                case "blue": {
                    bitmap.convertImageToBlue();
                    break;
                }
                case "green": {
                    bitmap.convertToGreen();
                    break;
                }
                default: {
                    System.out.println("incorrect transformation bitmap color");
                    break;
                }
            }
            bitmap.writeImage(args[1]);
        }
        catch (IOException exception) {
            exception.printStackTrace();
        }
    }
}
